[CASSH SERVER][1.6.1] Add exception for admin check and fix principals
leboncoin/cassh pull request #20
Opened 2018-09-18 16:04 UTC by nbeguier

- Add exception for admin check
  - fix principals

2018-09-18 17:38 UTC, aladjadj requested changes

2018-09-18 17:38 UTC, aladjadj commented on src/server/server.py
> +                memberof_list = ldap_conn.search_s(SERVER_OPTS['ldap_bind_dn'], 2,
replace '2' by a CONSTANT ( ex: ldap.SCOPE_SUBTREE )

2018-09-18 17:38 UTC, aladjadj commented on src/server/server.py
> +                                                   filterstr='(%s=%s)' % (SERVER_OPTS['filterstr'], realname)
maybe replace by filter
'(&(%s=%s)(memberOf=%s))'  % (SERVER_OPTS['filterstr'], realname, SERVER_OPTS['ldap_admin_cn'])
and except ldap.NO_SUCH_OBJECT

2018-09-19 07:14 UTC, nbeguier commented on src/server/server.py
> +                memberof_list = ldap_conn.search_s(SERVER_OPTS['ldap_bind_dn'], 2,
great !

2018-09-19 07:21 UTC, nbeguier commented on src/server/server.py
> +                                                   filterstr='(%s=%s)' % (SERVER_OPTS['filterstr'], realname)
Good point.
But, the return object is always a list of users, so there is no need of exception.

2018-09-19 07:44 UTC, nbeguier commented
@aladjadj Files are updated, thanks for your help

2018-09-19 09:26 UTC, xakraz commented on src/server/server.py
> +                return False, 'Error: user %s is not an admin.' % realname
:+1:

2018-09-19 09:27 UTC, xakraz approved these changes

2018-09-19 10:01 UTC, aladjadj commented on src/server/server.py
> +                return False, 'Error: user %s is not an admin.' % realname
:+1:

2018-09-19 10:01 UTC, aladjadj approved these changes

2018-09-19 10:02 UTC, merged